name: semantickitti_stc_kl_ablate_wcd0_ws0_wpc0_wr0_e200
dataset: semantickitti
data_path: data/users/minesawa/semantickitti/growsp
sp_path: data/users/minesawa/semantickitti/growsp_sp_1
original_data_path: data/dataset/semantickitti/dataset/sequences
patchwork_path: data/users/minesawa/semantickitti/patchwork
save_path: data/users/minesawa/semantickitti/semantickitti_stc_kl/ablation/semantickitti_stc_kl_ablate_wcd0_ws0_wpc0_wr0_e200
pseudo_label_path: pseudo_label_kitti/
sp_id_path: sp_id_kitti/
max_epoch:
- 100
- 100
max_iter:
- 10000
- 30000
bn_momentum: 0.02
conv1_kernel_size: 5
lr: 0.04
weight_decay: 0.01
accum_step: 2
workers: 4
cluster_workers: 24
eval_workers: 12
batch_size:
- 4
- 4
eval_batch_size: 8
cluster_batch_size: 1
persistent_workers: false
prefetch_factor: 4
use_ddp: true
ddp_backend: nccl
ddp_timeout_minutes: 180
seed: 2022
log_interval: 1000000
voxel_size: 0.15
input_dim: 3
primitive_num: 128
semantic_class: 19
feats_dim: 128
ignore_label: -1
growsp:
  start: 80
  end: 30
  drop_threshold: 10
  w_rgb: 1.0
  c_rgb: 5.0
  c_shape: 5.0
select_num: 6000
eval_select_num: 4071
r_crop: 50.0
frame_stride: 1
scan_window: 1
cluster_interval: 10
eval_interval: 10
silhouette: false
evaluation:
  distance_evaluation: true
  distance_bins:
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  moving_static_evaluation: true
early_stopping:
  enabled: false
  patience: 3
  min_delta: 0.15
  metric: val_mIoU
  mode: max
  rel_drop_window: 15
  overfit_drop: 0.3
debug: false
vis: false
vis_sp: false
resume: false
wandb_run_id: null
stc:
  enabled: true
  weight: 0.5
  voteflow_preprocess_path: data/dataset/semantickitti/voteflow_preprocess_0109
  sp_matching:
    weight_centroid_distance: 0.0
    weight_spread_similarity: 0.0
    weight_point_count_similarity: 0.0
    weight_remission_similarity: 0.0
    max_centroid_distance: 5.0
    min_score_threshold: 0.7
    min_sp_points: 10
    remove_ego_motion: false
    exclude_ground: false
  loss:
    type: kl
    temperature: 0.3
