accum_step: 1
batch_size:
- 16
- 16
bn_momentum: 0.02
cluster_interval: 10
cluster_workers: 24
conv1_kernel_size: 5
data_path: data/users/minesawa/semantickitti/growsp
debug: false
early_stopping:
  enabled: true
  metric: val_mIoU
  min_delta: 0.15
  mode: max
  overfit_drop: 0.3
  patience: 3
  rel_drop_window: 15
eval_interval: 10
eval_select_num: 4071
feats_dim: 128
growsp:
  c_rgb: 5.0
  c_shape: 5.0
  drop_threshold: 10
  end: 30
  start: 80
  w_rgb: 1.0
ignore_hdbscan_outliers: true
ignore_label: -1
input_dim: 3
lmb: 1.0
lr: 0.01
max_epoch:
- 100
- 350
name: test_stc
original_data_path: data/dataset/semantickitti/dataset/sequences
patchwork_path: data/users/minesawa/semantickitti/patchwork
primitive_num: 500
pseudo_label_path: pseudo_label_kitti/
r_crop: 50.0
resume: false
save_path: data/users/minesawa/semantickitti/growsp_model
scan_window: 2
seed: 2022
select_num: 1500
semantic_class: 19
silhouette: false
sp_path: data/users/minesawa/semantickitti/growsp_sp
stc:
  correspondence:
    distance_threshold: 0.3
    min_points: 5
  enabled: true
  loss:
    temperature: 0.1
  scene_flow:
    checkpoint: scene_flow/VoteFlow/checkpoints/voteflow_best_m8n128_ori.ckpt
    model: voteflow
    point_cloud_range:
    - -51.2
    - -51.2
    - -3
    - 51.2
    - 51.2
    - 3
    voxel_size:
    - 0.2
    - 0.2
    - 6
  weight: 1.0
tarl_lr: 0.0002
vis: false
voxel_size: 0.15
wandb_run_id: null
weight_decay: 0.01
workers: 24
